In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/student-mat.csv')

In [ ]:
df.head()

,school,sex,age,address,famsize,Parrent_status,Mother_edu,Father_edu,Mother_job,Father_job,...,Family_quality_reln,freetime_after_school,goout_with_friends,workday_alcohol_consum,weekend_alcohol_consum,health_status,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
df.tail()

,school,sex,age,address,famsize,Parrent_status,Mother_edu,Father_edu,Mother_job,Father_job,...,Family_quality_reln,freetime_after_school,goout_with_friends,workday_alcohol_consum,weekend_alcohol_consum,health_status,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
df.shape

(395, 33)

In [ ]:
df.describe()

,age,Mother_edu,Father_edu,traveltime,weekly_studytime,failures,Family_quality_reln,freetime_after_school,goout_with_friends,workday_alcohol_consum,weekend_alcohol_consum,health_status,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [ ]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Parrent_status',
       'Mother_edu', 'Father_edu', 'Mother_job', 'Father_job',
       'reason_to_chose_school', 'guardian', 'traveltime', 'weekly_studytime',
       'failures', 'extra_edu_supp', 'family_edu_supp', 'extra_paid_class',
       'extra_curr_activities', 'nursery', 'Interested_in_higher_edu',
       'internet_access', 'romantic_relationship', 'Family_quality_reln',
       'freetime_after_school', 'goout_with_friends', 'workday_alcohol_consum',
       'weekend_alcohol_consum', 'health_status', 'absences', 'G1', 'G2',
       'G3'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   school                    395 non-null    object
 1   sex                       395 non-null    object
 2   age                       395 non-null    int64
 3   address                   395 non-null    object
 4   famsize                   395 non-null    object
 5   Parrent_status            395 non-null    object
 6   Mother_edu                395 non-null    int64
 7   Father_edu                395 non-null    int64
 8   Mother_job                395 non-null    object
 9   Father_job                395 non-null    object
 10  reason_to_chose_school    395 non-null    object
 11  guardian                  395 non-null    object
 12  traveltime                395 non-null    int64
 13  weekly_studytime          395 non-null    int64
 14  failures                  395 non-null    int64
 15  extra_edu_supp            395 non-null    object
 16  family_edu_supp           395 non-null    object
 17  extra_paid_class          395 non-null    object
 18  extra_curr_activities     395 non-null    object
 19  nursery                   395 non-null    object
 20  Interested_in_higher_edu  395 non-null    object
 21  internet_access           395 non-null    object
 22  romantic_relationship     395 non-null    object
 23  Family_quality_reln       395 non-null    int64
 24  freetime_after_school     395 non-null    int64
 25  goout_with_friends        395 non-null    int64
 26  workday_alcohol_consum    395 non-null    int64
 27  weekend_alcohol_consum    395 non-null    int64
 28  health_status             395 non-null    int64
 29  absences                  395 non-null    int64
 30  G1                        395 non-null    int64
 31  G2                        395 non-null    int64
 32  G3                        395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [ ]:
df.isnull().sum()

school                      0
sex                         0
age                         0
address                     0
famsize                     0
Parrent_status              0
Mother_edu                  0
Father_edu                  0
Mother_job                  0
Father_job                  0
reason_to_chose_school      0
guardian                    0
traveltime                  0
weekly_studytime            0
failures                    0
extra_edu_supp              0
family_edu_supp             0
extra_paid_class            0
extra_curr_activities       0
nursery                     0
Interested_in_higher_edu    0
internet_access             0
romantic_relationship       0
Family_quality_reln         0
freetime_after_school       0
goout_with_friends          0
workday_alcohol_consum      0
weekend_alcohol_consum      0
health_status               0
absences                    0
G1                          0
G2                          0
G3                          0
dtype: int64

In [ ]:
df['G3'].unique()

array([ 6, 10, 15, 11, 19,  9, 12, 14, 16,  5,  8, 17, 18, 13, 20,  7,  0,
        4])

In [ ]:
df[df['health_status']>2]

,school,sex,age,address,famsize,Parrent_status,Mother_edu,Father_edu,Mother_job,Father_job,...,Family_quality_reln,freetime_after_school,goout_with_friends,workday_alcohol_consum,weekend_alcohol_consum,health_status,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,0,6,5,0
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [ ]:
a=df.loc[1:4,'health_status']

In [ ]:
df.iloc[1:10,0:2]

  school sex
1     GP   F
2     GP   F
3     GP   F
4     GP   F
5     GP   M
6     GP   M
7     GP   F
8     GP   M
9     GP   M

In [ ]:
gg=df.groupby('health_status')['health_status'].mean()

In [ ]:
gg

health_status
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
Name: health_status, dtype: float64

In [ ]:
g1=df.groupby('health_status')['health_status'].std()
g2=df.groupby('health_status')['health_status'].median()
g3=df.groupby('health_status')['health_status'].size()

In [ ]:
g1

health_status
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
Name: health_status, dtype: float64

In [ ]:
g2

health_status
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
Name: health_status, dtype: float64

In [ ]:
g3

health_status
1     47
2     45
3     91
4     66
5    146
Name: health_status, dtype: int64

In [ ]:
da1=df.sort_values(by='health_status')
da1.head()

,school,sex,age,address,famsize,Parrent_status,Mother_edu,Father_edu,Mother_job,Father_job,...,Family_quality_reln,freetime_after_school,goout_with_friends,workday_alcohol_consum,weekend_alcohol_consum,health_status,absences,G1,G2,G3
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,4,15,16,15
363,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,2,3,4,1,1,1,0,16,15,15
367,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,7,6,0
345,GP,F,18,U,GT3,T,3,2,other,services,...,5,4,3,2,3,1,7,13,13,14
43,GP,M,15,U,GT3,T,2,2,services,services,...,5,4,1,1,1,1,0,8,8,11

In [ ]:

import numpy as np
import pandas as pd

# Creating a sample dataframe with missing values
# FIXED: Added 'Unknown' to ensure all lists have 4 elements
data = {
    'Name': ['Malini', 'Kavi', 'Sridevi', 'Unknown'],
    'Score': [99, np.nan, 95, np.nan],
    'City': ['Chennai', 'Ambattur', np.nan, 'Thiruvallur']
}

df_sample = pd.DataFrame(data)

# Fill all NaN values with 0
df_filled = df_sample.fillna(0)

print(df_filled)

      Name  Score         City
0   Malini   99.0      Chennai
1     Kavi    0.0     Ambattur
2  Sridevi   95.0            0
3  Unknown    0.0  Thiruvallur

In [ ]:
da1=df.copy()
da1.insert(0,'Type', 'Student')
da1.head()

,Type,school,sex,age,address,famsize,Parrent_status,Mother_edu,Father_edu,Mother_job,...,Family_quality_reln,freetime_after_school,goout_with_friends,workday_alcohol_consum,weekend_alcohol_consum,health_status,absences,G1,G2,G3
0,Student,GP,F,18,U,GT3,A,4,4,at_home,...,4,3,4,1,1,3,6,5,6,6
1,Student,GP,F,17,U,GT3,T,1,1,at_home,...,5,3,3,1,1,3,4,5,5,6
2,Student,GP,F,15,U,LE3,T,1,1,at_home,...,4,3,2,2,3,3,10,7,8,10
3,Student,GP,F,15,U,GT3,T,4,2,health,...,3,2,2,1,1,5,2,15,14,15
4,Student,GP,F,16,U,GT3,T,3,3,other,...,4,3,2,1,2,5,4,6,10,10